name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to the branch `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.14

    - name: Install dependencies
      run: |
        pip install -r community-handbook/requirements.txt


    # Build the book
    - name: Build the book
      run: |
        jupyter-book build community-handbook/

    # Push the book's HTML to branch 'gh-pages'. Note this branch will then be deleted by the action
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./community-handbook/_build/html
  # Make sure that in the GitHub pages settings on github, the build source via github actions